[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
type-macro = { version = "0.1.0", path = "../type-macro" }
uuid = "1.3.1"
